# -*- coding: utf-8 -*-
"""Belajar Fungsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NY2izZnpyo2VHIdAW9q9Y36GCl1Xjsj9
"""

# Membuat Fungsi
def salam():
    print ("Hello, Ohayo Gozaimasu")

## Pemanggilan Fungsi
salam()
salam()
salam()

def nilai(ucapan):
    print(ucapan)
salam("Selamat Anda Kena JP")

# Membuat fungsi dengan parameter
def luas_segitiga(alas, tinggi):
  luas = (alas * tinggi) / 2
  print ("Luas segitiga: %f"  %luas)

# Pemanggilan fungsi
luas_segitiga(40,10)

def luas_persegi(sisi):
  luas = sisi * sisi
  return luas

# pemanggilan fungsi
print("Luas persegi: %d" % luas_persegi (800))

def volume_persegi(luas):
  volume = luas * luas
  return volume
print("Volume persegi: %d" % volume_persegi(640000))

# membuat variabel global
nama = "Belajar Mengiklaskan Dia, Dengan Masa lalunya"
versi = "Orang baru"

def help():
  # ini variabel lokal
  nama = "Badutmu"
  versi = "Part 1 & 2"
  # mengakses variabel lokal
  print ("Nama: %s" % nama)
  print ("Versi: %s" % versi)

# mengakses variabel global
print ("Nama: %s" % nama)
print ("Versi: %s" % versi)

# memanggil fungsi help()
help()

# membuat variabel global
nama = "Aditiya"
tanggal_lahir = "10-Februari-2005"

def biodata():
  # ini variabel lokal
  hobi = "Bermain Have fun"
  jurusan = "ILKOM"
  tempat_tinggal = "Desa Serdang"
  # mengakses variabel lokal
  print ("Hobi: %s" % hobi)
  print ("Jurusan: %s" % jurusan)
  print ("Tempat_tinggal: %s" % tempat_tinggal)

# mengakses varibael global
print ("Nama: %s" % nama)
print ("Tanggal_lahir: %s" % tanggal_lahir)

# memanggil fungsi biodata()
biodata()











# Variabel global untuk menyimpan buku
buku =[]

# fungsi untuk menampilkan semua data
def show_data():
  if len(buku) <= 0:
    print("BELUM ADA DATA")
  else:
    for indeks in range(len(buku)):
      print("[{}] {}".format(indeks, buku[indeks]))

# fungsi untuk menambah data
def insert_data():
    buku_baru = input("Judul Buku: ")
    buku.append(buku_baru)

# fungsi untuk edit data
def edit_data():
  show_data()
  indeks = int(input("Inputkan ID buku: "))
  if indeks > len(buku):
      print("ID salah")
  else:
      judul_baru = input("Judul baru: ")
      buku[indeks] = judul_baru

# fungsi untuk edit data
def delete_data():
  show_data()
  indeks = int(input("Inputkan ID buku: "))
  if indeks > len(buku) :
       print("ID salah")
  else:
      buku.remove(buku[indeks])

# fungsi untuk menampilkan menu
def show_menu():
    print("\n")
    print("------------ MENU ----------")
    print("[1] Show Data")
    print("[2] Insert Data")
    print("[3] Edit Data ")
    print("[4] Delete Data")
    print("[5] Exit")

    menu = input("PILIH MENU> ")
    print("\n")

    if int(menu) == 1:
      show_data()
    elif int(menu) == 2:
      insert_data()
    elif int(menu) == 3:
      edit_data()
    elif int(menu) == 4:
       delete_data()
    elif int(menu) == 5:
       exit()
    else:
       print("Salah pilih!")

if __name__ == "__main__":

    while True:
      show_menu()

