# -*- coding: utf-8 -*-
"""Latihan If Elif Else

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRVoDI9CfCgKwdfxVP_-hHSmeFQ7MyVz
"""

print('Dolphin', end=' ')
print('ML', end=' ')

a = 5
b = 6
print('a','+', 'b', '=', 'c')

if True :
  print('Kode program ini akan dieksekusi')

if False :
  prrint('Kode program ini tidak akan dieksekusi')
print('Kode program ini akan selalu dieksekusi karena tidak termasuk pada percobaan')

nilai = int(input('Masukkan Nilai Anda'))
print('Nilai anda adalah:', nilai, '/A')
if nilai >= 90:
  print('Selamat, anda lulus!')
else :
  print('Maaf, anda tidak lulus.')

nilai =int(input('Masukkkan Nilai: '))

if nilai >= 90:
  print('Predikat A')
elif nilai >= 80:
  print('Predikat B')
elif nilai >= 60:
  print('Predikat C')
elif nilai >= 40:
  print('Predikat D')
else :
  print('Predikat E')

buah_yang_tersedia = ['jeruk', 'mangga', 'melon']
buah_yang_dicari = input('Masukkan nama buah dalam huruf kecil: ')

if (buah_yang_dicari in buah_yang_tersedia):
  print('Buah yang anda cari tersedia!')
else :
  print('Buah yang anda cari tidak tersedia!')

nilai = int(input('Masukkan Nilai: '))
usia = int(input('Masukkan usia: '))

if nilai >= 75:
  if (usia < 15):
    print('Selamat Dek, kamu lulus!')
  else:
    print('Selamat Kak, kamu lulus!')
else:
  if (usia < 15):
    print('NT, ya dek!')
  else :
    print('NT, ya kak!')