# -*- coding: utf-8 -*-
"""Perulangan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19L9BVVVi8-kkwrd-l6u0D2UETl_OHOGK
"""

listDesa = ['Serdang', 'Jeriji', 'Bikang', 'Gadung', 'Pergam', 'Airgegas', 'Toboali']
for desa in listDesa :
  print(desa)

listDesa = ['Serdang', 'Jeriji', 'Bikang', 'Gadung', 'Pergam', 'Airgegas', 'Toboali']
for i, desa in enumerate(listDesa) :
  print(desa)

## 0 sampai 8
for i in range(9):
  print("Perulangan ke -", i)

## 25 sampai 35
for i in range(25, 36):
  print('i =',i)

## Bilangan Ganjil kelipatan 3
for i in range(3, 15, 3):
  print('i = ', i)

## Bilangan genap kelipatan 2
for bilangan_genap in range(2, 16, 2):
  print(bilangan_genap)

tupleBuah = ('Jeruk', 'Anggur', 'Nanas', 'Cerry', 'Kelengkeng')
for buah in tupleBuah:
  print(buah)

for karakter in "Serdang":
  print(karakter)

for i in range(20, 30):
  # skip jika i == 23
  if ( i == 23):
    continue
  print(i)

for i in range (20, 30):
  # hentikan jika i == 25
  if (i == 25):
    break
  print(i)

listDesa = ['Serdang', 'Jeriji', 'Bikang', 'Gadung', 'Pergam', 'Airgegas', 'Toboali']
for desa in listDesa :
  print(desa)
else:
  print('Tidak ada lagi item yang tersisa')

listDesa = ['Serdang', 'Jeriji', 'Bikang', 'Gadung', 'Pergam', 'Airgegas', 'Toboali']
desaYangDicari = input('Ketik Nama Desa Yang Kamu Cari: ')

for i, desa in enumerate(listDesa):
  # kita ubah katanya ke Lowercase agar
  # menjadi case insensitive
  if desa.lower() == desaYangDicari.lower():
    print('Desa Yang Anda Cari Beranda Pada Indeks', i)
    break
else :
  print('Maaf, Desa Yang Anda Cari Tidak Ada')

listDesa = ['Serdang', 'Jeriji', 'Bikang', 'Gadung', 'Pergam', 'Airgegas', 'Toboali']
desaYangDicari = input('Ketik Nama Desa Yang Kamu Cari: ')

for i, desa in enumerate(listDesa):
  # kita ubah katanya ke Lowercase agar
  # menjadi case insensitive
  if desa.lower() == desaYangDicari.lower():
    print('Desa Yang Anda Cari Beranda Pada Indeks', i)
    break
else :
  print('Maaf, Desa Yang Anda Cari Tidak Ada')

