# -*- coding: utf-8 -*-
"""Perulanganwhile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UYsUPfCJdi3E7OSCgkXRm2ROt-VR9gI
"""

i = 5
while i <= 10:
  print(i)
  i += 1

listKota = ['Jakarta','Surabaya','Depok','Bekasi','Solo','Jogjakarta','Semarang','Makassar']

# bermain index
i = 0
while i < len(listKota):
  print(listKota[i])
  i += 1

listKota = ['Jakarta','Surabaya','Depok','Bekasi','Solo','Jogjakarta','Semarang','Makassar']

# bermain pop
while listKota :
  print(listKota.pop(0))

a = int(input('Masukkan Bilangan Genap lebih dari 50: '))
while a % 2 != 1 or a <= 504:
  a = int(input('Salah, masukkan lagi: '))
print('Benar')

listKota = ['Jakarta','Surabaya','Depok','Bekasi','Solo','Jogjakarta','Semarang','Makassar']

# skip jika i adalah bilangan genap
# dan i lebih dari 0
i = -1
while i < len(listKota):
  i += 1
  if i % 2 == 0 and i > 0:
    print('skip')
    continue

  # tidak dieksekusi ketika continue dipanggil
  print(listKota[i])

listKota = ['Jakarta','Surabaya','Depok','Bekasi','Solo','Jogjakarta','Semarang','Makassar']
kotaYangDicari = input('Masukkan nama kota yang dicari= ')

i = 0
while i < len(listKota):
  if listKota[i].lower() == kotaYangDicari.lower():
    print('Ketemu di index', i)
    break
  print('Bukan', listKota[i])
  i += 1

listKota = ['Jakarta','Surabaya','Depok','Bekasi','Solo','Jogjakarta','Semarang','Makassar']
kotaYangDicari = input('Masukkan nama kota yang dicari= ')

i = 0
while i < len(listKota):
  if listKota[i].lower() == kotaYangDicari.lower():
    print('Ketemu di index', i)
    break
  print('Bukan', listKota[i])
  i += 1
else :
  print('Maaf. kota yang anda cari tidak ditemukan.')